-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\receive_OK\receive_OK.vhd
-- Created: 2017-07-19 14:31:12
-- 
-- Generated by MATLAB 8.6 and HDL Coder 3.7
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0
-- Target subsystem base rate: 0
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        0
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Out1                          ce_out        0
-- Out2                          ce_out        0
-- Out3                          ce_out        0
-- Out4                          ce_out        0
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: receive_OK
-- Source Path: receive_OK
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY receive_OK IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        In1                               :   IN    std_logic;
        In2                               :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        ce_out                            :   OUT   std_logic;
        Out1                              :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
        Out2                              :   OUT   std_logic;
        Out3                              :   OUT   std_logic;
        Out4                              :   OUT   std_logic_vector(7 DOWNTO 0)  -- uint8
        );
END receive_OK;


ARCHITECTURE rtl OF receive_OK IS

  -- Component Declarations
  COMPONENT WiFi_Receiver_mac
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          data_stream_in_stb              :   IN    std_logic;
          data_stream_in                  :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          model_cmd                       :   OUT   std_logic_vector(3 DOWNTO 0);  -- ufix4
          rec_cmd_en                      :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : WiFi_Receiver_mac
    USE ENTITY work.WiFi_Receiver_mac(rtl);

  -- Signals
  SIGNAL model_cmd                        : std_logic_vector(3 DOWNTO 0);  -- ufix4
  SIGNAL rec_cmd_en                       : std_logic;

BEGIN
  u_WiFi_Receiver_mac : WiFi_Receiver_mac
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              data_stream_in_stb => In1,
              data_stream_in => In2,  -- uint8
              model_cmd => model_cmd,  -- ufix4
              rec_cmd_en => rec_cmd_en
              );

  ce_out <= clk_enable;

  Out1 <= model_cmd;

  Out2 <= rec_cmd_en;

  Out3 <= In1;

  Out4 <= In2;

END rtl;

